[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pychanasync"
version = "0.1.0"
description = "Async channel implementation for Python"
authors = [{ name = "Gwalisam Matthew" }]
requires-python = ">=3.11"
dependencies = []

